export { default as AboutPage } from './AboutPage.vue'
export { default as HomePage } from './HomePage.vue'
export { default as ReceptionPage } from './ReceptionPage.vue'
export { default as LoginPage } from './LoginPage.vue'
export { default as CategoriesPage } from './CategoriesPage.vue'